---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

We're going to make some plotly plots.


## Load packages and data


```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

Lets get some data,

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```


Lets make a scatterplot!!!

```{r}
nyc_airbnb %>% 
  mutate(text_label = str_c("Price: ", price)) %>% 
  plot_ly(
    x = ~lat, y = ~long, color = ~ price,
    type = "scatter", mode = "markers",
    alpha = 0.5, text = ~text_label 
  )
```


Can we make boxplot? 

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>%
  plot_ly(y = ~ price, color = ~ neighbourhood,
          type = "box", colors = "viridis")
```


Can we make a bar plot?

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
    mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>%
  plot_ly( x= ~neighbourhood, y = ~n,
           type = "bar")
```


## ggplot??


```{r}
ggp_scatterplot = 
  nyc_airbnb %>% 
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point()

ggplotly(ggp_scatterplot)
```
 


